---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmsr
  labels:
    app: vmsr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vmsr
  template:
    metadata:
      labels:
        app: vmsr
    spec:
      containers:
        - name: vmsr
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 2
          image: acrsbxdevaks.azurecr.io/vmsr:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 30467
          env:
            - name: REGSERVER_URL
              value: http://igs:igscd@regserver:30000/eureka/
          lifecycle:
            preStop:
              httpGet:
                path: /maintain/stop
                port: 30467
                scheme: HTTP
          livenessProbe:
            httpGet:
              path: /health/status
              port: 30467
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 30467
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 5
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: acr-secret-pwd